name: tony chen - blog
author: Tony Chen
email: chen.tony@mit.edu
description: Notes from tony chen on statistics, machine learning, and AI
url: "chentoast.github.io"
baseurl: "/notes"
markdown: kramdown
highlighter: rouge
kramdown:
    input: GFM
    syntax_highlighter: rouge
