baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'notes with <3, from tony'
summary = 'unfinished and unorganized notes'

theme = 'mini'
showToc = true
refLinksErrorLevel = "WARNING"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['$$', '$$']]
          inline = [['\(', '\)']]
    [markup.goldmark.renderer]
      hardWraps = true

[params]
  math = true
  author = 'tony chen'
